### ISSUE TITLE
Splitting the repository

### ISSUE THREAD

**Issue by aib** [bagerakbay/mahlas#4]
Along which lines should we do it, @bagerakbay ?

**Comment by bagerakbay** [comment]
files on the root will stay here since this repository is for the web. All the folders and files in them will move to docs repository

**Comment by aib** [comment]
Done. Please review the `new-web` and `new-docs` branches. I'll update `master` and `docs/master` if they seem okay.

**Comment by bagerakbay** [comment]
terminology.md and waysToStart.md should be  in the docs repository. The rest seems to be ok. 
mahlas-network.github.io should be named as it is, probably github pages need this for the domain, so contents of the new-web should stay in mahlas-network.github.io. Maybe you can just split for the docs and delete them from the original.

**Comment by aib** [comment]
Aight, check again please

**Comment by bagerakbay** [comment]
seems perfect.

**Comment by aib** [comment]
Updated corresponding repositories, any other problems beyond this point should have their own issues.
